CREATE TABLE [EndPointProvider].[EndpointHosts]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [Host] VARCHAR(MAX) NOT NULL, 
    [Name] VARCHAR(MAX) NOT NULL, 
    [CreatedDate] DATETIME NOT NULL DEFAULT GETDATE(), 
    [LastUpdatedDate] DATETIME NOT NULL DEFAULT GETDATE(), 
)
